# Generated by Django 5.0.6 on 2024-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Title', models.CharField(max_length=30)),
                ('ReleasedYear', models.IntegerField(max_length=4)),
                ('Description', models.TextField()),
            ],
        ),
    ]
