# Generated by Django 5.0.6 on 2024-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb',
            name='ReleasedYear',
            field=models.IntegerField(),
        ),
    ]
