# Generated by Django 5.0.6 on 2024-05-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_alter_moviedb_releasedyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DirectorName', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='moviedb',
            name='ReleasedYear',
            field=models.IntegerField(null=True),
        ),
    ]
