# Generated by Django 5.0.6 on 2024-05-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_censorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='censoredBy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='MovieApp.censorinfo'),
        ),
    ]
