# Generated by Django 5.0.6 on 2024-05-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0006_moviedb_censoredby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedb',
            old_name='censoredBy',
            new_name='certifedBy',
        ),
    ]
