# Generated by Django 5.0.6 on 2024-05-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0008_rename_certifedby_moviedb_censoredby'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='movieDirector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MovieApp.director'),
        ),
    ]
