# Generated by Django 5.0.6 on 2024-05-29 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0009_moviedb_moviedirector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb',
            name='movieDirector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directedBy', to='MovieApp.director'),
        ),
    ]
