# Generated by Django 5.0.6 on 2024-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0010_alter_moviedb_moviedirector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='moviedb',
            name='cast',
            field=models.ManyToManyField(related_name='moviecast', to='MovieApp.actor'),
        ),
    ]
